//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Web.Mvc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Web.Mvc.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred and the file could not be downloaded..
        /// </summary>
        internal static string ExportException {
            get {
                return ResourceManager.GetString("ExportException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The container could not resolve a type for &apos;{0}&apos;. Please verify if the implementation has been registered..
        /// </summary>
        internal static string FWImplementationNotFoundException {
            get {
                return ResourceManager.GetString("FWImplementationNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &quot;{0}&quot; is not of the valid type &quot;{1}&quot;..
        /// </summary>
        internal static string FWInvalidPropertyTypeException {
            get {
                return ResourceManager.GetString("FWInvalidPropertyTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate the attribute {0}..
        /// </summary>
        internal static string FWMissingAttributeException {
            get {
                return ResourceManager.GetString("FWMissingAttributeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No datasource was found for the property &apos;{0}&apos;..
        /// </summary>
        internal static string FWMissingDatasourceException {
            get {
                return ResourceManager.GetString("FWMissingDatasourceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element {0} is missing a template..
        /// </summary>
        internal static string FWMissingTemplateException {
            get {
                return ResourceManager.GetString("FWMissingTemplateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Key attributes were defined within the {0} class..
        /// </summary>
        internal static string FWMultipleKeyException {
            get {
                return ResourceManager.GetString("FWMultipleKeyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RenderScripts invocation is invalid for this view. It cannot be called by partial pages..
        /// </summary>
        internal static string FWRenderScripts_MethodCannotBeCalled {
            get {
                return ResourceManager.GetString("FWRenderScripts_MethodCannotBeCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires a child action to work..
        /// </summary>
        internal static string FWRequiredChildActionException {
            get {
                return ResourceManager.GetString("FWRequiredChildActionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string FWWeekdays_Friday {
            get {
                return ResourceManager.GetString("FWWeekdays_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string FWWeekdays_Monday {
            get {
                return ResourceManager.GetString("FWWeekdays_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string FWWeekdays_Saturday {
            get {
                return ResourceManager.GetString("FWWeekdays_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string FWWeekdays_Sunday {
            get {
                return ResourceManager.GetString("FWWeekdays_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string FWWeekdays_Thursday {
            get {
                return ResourceManager.GetString("FWWeekdays_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string FWWeekdays_Tuesday {
            get {
                return ResourceManager.GetString("FWWeekdays_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string FWWeekdays_Wednesday {
            get {
                return ResourceManager.GetString("FWWeekdays_Wednesday", resourceCulture);
            }
        }
    }
}
