//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Web.Security.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Web.Security.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed. Invalid user and/or password..
        /// </summary>
        internal static string FWAuthenticationException {
            get {
                return ResourceManager.GetString("FWAuthenticationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must have at least 1 numeric character..
        /// </summary>
        internal static string FWInvalidPassword_RequireDigit {
            get {
                return ResourceManager.GetString("FWInvalidPassword_RequireDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must have a minimum of {0} characters..
        /// </summary>
        internal static string FWInvalidPassword_RequiredLength {
            get {
                return ResourceManager.GetString("FWInvalidPassword_RequiredLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must have at least {0} unique characters..
        /// </summary>
        internal static string FWInvalidPassword_RequiredUniqueChars {
            get {
                return ResourceManager.GetString("FWInvalidPassword_RequiredUniqueChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must have at least 1 lowercase character..
        /// </summary>
        internal static string FWInvalidPassword_RequireLowercase {
            get {
                return ResourceManager.GetString("FWInvalidPassword_RequireLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must have at least 1 non-alphanumeric character..
        /// </summary>
        internal static string FWInvalidPassword_RequireNonAlphanumeric {
            get {
                return ResourceManager.GetString("FWInvalidPassword_RequireNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must have at least 1 uppercase character..
        /// </summary>
        internal static string FWInvalidPassword_RequireUppercase {
            get {
                return ResourceManager.GetString("FWInvalidPassword_RequireUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm you are not a robot..
        /// </summary>
        internal static string FWRecaptcha_Invalid {
            get {
                return ResourceManager.GetString("FWRecaptcha_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReCatpcha server could not be reached..
        /// </summary>
        internal static string FWRecaptcha_NoResponse {
            get {
                return ResourceManager.GetString("FWRecaptcha_NoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reCaptcha Token found..
        /// </summary>
        internal static string FWRecaptcha_NoToken {
            get {
                return ResourceManager.GetString("FWRecaptcha_NoToken", resourceCulture);
            }
        }
    }
}
